BarnesFoundation/Barnes-Online-Collection

src/scss/_mixins.scss
src/scss/styleguide-extend.scss
src/scss/variables.scss

Fixes style dependencies that were broken for the prod build on the last pr

fixing style dependencies

---

package.json

adding missing package.json module

doh - forgot to save this module when i installed it

---

src/components-barnes-toolkit/components/nav/Nav.jsx
src/components/SiteHeader/SiteHeader.jsx

and removing the un-needed and non-canonical .php extension

updating "our collection" links

---

src/layouts/ArtObjectPage/PanelDetails/index.jsx
src/reducers/objects.js

this one does not have the _o.jpg at the end of it.

adding new url for the wufoo form

---

src/actions/object.js

This at least stops the infinite loop happening, but we should figure out how to throw a 404 before it even gets here...

Stop infinite request loop on invalid object id

---

package-lock.json
server/app.js
src/actions/object.js
src/actions/objects.js
src/actions/relatedObjects.js

Implement custom similarity endpoint

---

server/app.js

This should make similar items be more similar

Consider people in distance calculation

---

server/app.js

I mistook the sorting, this should fix similar/surprising

Fix sort order for similar/surprising

---

src/components/ArtObjectPageComponents/TabbedSubMenu/FlickityMenu.jsx
src/components/ArtObjectPageComponents/TabbedSubMenu/index.jsx

This solves the js error as well.

refactoring flickity into its own module.

---

src/actions/filters.js
src/actions/objects.js
src/components/CollectionFilters/Filter.jsx
src/components/CollectionFilters/LineFilters.jsx
src/components/CollectionFilters/collectionFilters.scss
src/reducers/filterSets.js
src/reducers/filters.js
src/reducers/mobileFilters.js

Solves https://trello.com/c/KKwKoMCf/249-reduce-selection-of-a-single-element

Force single filter selection

---

server/app.js

This reverts commit f789e79111d32812ba8e3f8b8bbf88aa7e4366f0.

Revert "Swap distance calc for related"

---

server/app.js
src/actions/relatedObjects.js

Fix similar/surprising slider once and for all

---

package-lock.json
src/components/ArtObjectPageComponents/PanelDetails/SummaryTable.jsx
src/components/ArtObjectPageComponents/PanelDetails/index.jsx
src/components/ArtObjectPageComponents/PanelEnsemble/index.jsx
src/ensembleIndex.js

Add provenance

---

src/components/CollectionFilters/CollectionFiltersApplied.jsx
src/components/CollectionFilters/ColorFilters.jsx
src/components/CollectionFilters/MobileFiltersMenu.jsx
src/components/CollectionFilters/MobilePanelShuffleButton.jsx
src/components/CollectionFilters/collectionFilters.scss
src/layouts/LandingPage/landingPage.scss

shuffle button for mobile

---

src/components/ArtObjectPageComponents/ArtObjectPageShell/index.scss

see if this addresses the sticky scrolling on mobile issue. https://trello.com/c/HLUmIkDv/276-scrolling-visually-related-in-mobile-feels-sticky

not on mobile

---

src/components/CollectionFilters/mobileFilters.scss
src/components/Modal/index.scss
src/scss/styleguide-extend.scss

this time for sure

---

server/app.js

adding tracking url for downloading images.

adding tracking url for downloading images

---

server/app.js
src/actions/objects.js
src/components/AccordionMenu/index.scss
src/components/ArtObjectGrid/artObjectGrid.scss
src/components/ArtObjectPageComponents/ArtObjectPageShell/index.scss
src/components/ArtObjectPageComponents/PanelDetails/SummaryTable.jsx
src/components/ArtObjectPageComponents/PanelDetails/index.jsx
src/components/ArtObjectPageComponents/PanelVisuallyRelated/index.jsx
src/components/ArtObjectPageComponents/TabbedSubMenu/FlickityMenu.jsx
src/components/CollectionFilters/CollectionFiltersApplied.jsx
src/components/CollectionFilters/MobileSearchMenu.jsx
src/layouts/LandingPage/landingPage.scss
src/scss/styleguide-extend.scss

print styles for https://trello.com/c/LIqnj0hg/129-print-css-4

Print styles

---

package-lock.json
src/components/Footer/Footer.jsx
src/scss/styleguide-extend.scss
src/scss/variables.scss

Accessibility

---

server/app.js
src/actions/objects.js
src/helpers.js

Addresses https://trello.com/c/kEJYhV65/248-display-results-on-all-pages-before-more-never-change. Adds randomness to the home page search of 'highlight' objects

Randomizer

---

README.md

just updating the readme with info about the sitemap script

add note in the readme about the sitemap generation script

---

src/components/Footer/Footer.jsx

In the Knight Foundation Credit line there was a missing space between the words "support" and "from. This PR fixes that small typo.

Fix typo in knight foundation credit line

---

src/components/SiteHeader/SiteHeader.jsx

- Adds back in `height` for all `logo100sizes`

add back in height attribute for logo100sizes

---

src/components/Footer/Footer.jsx

- Update made to footer of collection site to reflect new Thu-Mon hours
https://barnesfoundation.atlassian.net/browse/CS-30

update hours from Fri-Mon to Thu-Mon

---

server/constants/tours/eyeSpy/feb-2022.json

- Changes to museum hours in footer
- Update dependencies: `follow-redirects` and `yargs-parser`

Release 2/15/22

---

public/sitemap.xml
server/constants/tours/eyeSpy/apr-2022.json
server/constants/tours/eyeSpy/index.js

April eye spy

---

src/components/EyeSpyPage/EyeSpyPage.jsx
src/components/NotFound/notFound.jsx
src/components/NotFound/notFound.scss
src/components/SiteHeader/SiteHeader.jsx
src/components/SiteHeader/siteHeader.scss
src/components/TourPage/TourPage.jsx
src/routeSwitcher.jsx

- created 404 `NotFound` component
- created a wildcard route path `*` that renders 404 page for invalid links
https://barnesfoundation.atlassian.net/browse/CS-19

Cs 19 -- 404 Page

---

src/components/SiteHeader/SiteHeader.jsx

I commented out conditional logic for rendering 100 logo based on year. This way when we get an end date for displaying this logo we can just uncomment the code and change the date.

100 Logo Extension

---

src/components/SiteHeader/SiteHeader.jsx

- Remove conditional logic that would switch to the basic Barnes logo on Jan 1, 2023

Release 12/21/22

---

.env-example
public/index.html
server/app.js
server/services/damsService.js
src/components/ArtObjectPageComponents/PanelDetails/index.jsx

https://barnesfoundation.atlassian.net/browse/DAMS-8

DAMS-8-render-alternative-renditions-on-collection-website

---

src/components/ArtObjectPageComponents/PanelDetails/index.jsx

https://barnesfoundation.atlassian.net/browse/DAMS-9
This pull request just adjusts rendering the caption for an image using the NetX caption if renditions exists. Otherwise, we'll fall back to the default.

DAMS-9-pull-captions-for-different-assets-from-different-fields

---

server/services/damsService/damsService.js
src/routeSwitcher.jsx

Turn off archive images for now

Merge development

---

src/components/SideMenu/SideMenu.jsx

Quick update to include new Research link and some link updates from Editorial team.
https://barnesfoundation.atlassian.net/browse/CS-48

CS-48 update site menu

---

src/components/Footer/Footer.jsx

- Update footer to match main site at Editorial Team's request
https://barnesfoundation.atlassian.net/browse/CS-51

CS-51 update footer to match main site

---

server/services/tourService.js
src/components/StickyListSection/StickyListSection.jsx
src/components/TourPage/TourPage.jsx
src/components/TourPage/tourPageHelper.js
src/components/TourPage/tourPageHelper.test.js

Makes a few tweaks to the tours/eye-spy hunts to remove room numbers from the UI, which will make it more difficult for adult audiences. 
You can test this using the YPN test tour, `/eye-spy/ypn-test`. 
https://barnesfoundation.atlassian.net/browse/CS-52

Cs 52 young professionals night updates
